services:
  bookbinder-app:
    environment:
      BASE: 'https://momijizukamori.github.io/bookbinder-js/'
    image: node:20
    volumes:
      - .:/app
    command: bash -c "cd /app && npm install && npm run build"

  bookbinder-nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html
