const base_config = {
  printFile: 'both',
  sourceRotation: 'none',
  rotatePage: false,
  paperSize: 'A4',
  paperSizeUnit: 'pt',
  printerType: 'duplex',
  paperRotation90: false,
  pageLayout: 'folio',
  cropMarks: false,
  cutMarks: false,
  pdfEdgeMarks: false,
  sigOrderMarks: false,
  pageScaling: 'lockratio',
  pagePositioning: 'centered',
  mainForeEdgePaddingPt: 0,
  bindingEdgePaddingPt: 0,
  topEdgePaddingPt: 0,
  bottomEdgePaddingPt: 0,
  sigFormat: 'standardsig',
  sigLength: 4,
  customSigLength: [0],
  foreEdgePaddingPt: 0,
  wackySpacing: 'wacky_pack',
  flyleafs: 1,
  sewingMarksEnabled: false,
  sewingMarkLocation: 'all',
  sewingMarksMarginPt: 72,
  sewingMarksAmount: 3,
  sewingMarksTapeWidthPt: 36,
  paperSizeCustomWidth: 0,
  paperSizeCustomHeight: 0,
};
export const testCases = {
  basic_duplex_folio: {
    input: 'example_page_numbers.pdf',
    config: base_config,
  },
  basic_duplex_quarto: {
    input: 'example_page_numbers.pdf',
    config: {
      ...base_config,
      pageLayout: 'quarto',
      flyleafs: 0,
    },
  },
  page_numbers_octavo_with_margin: {
    input: 'example_page_numbers.pdf',
    config: {
      printFile: 'both',
      sourceRotation: 'none',
      rotatePage: false,
      paperSize: 'A4',
      paperSizeUnit: 'pt',
      printerType: 'duplex',
      paperRotation90: false,
      pageLayout: 'octavo',
      cropMarks: false,
      cutMarks: false,
      pdfEdgeMarks: false,
      sigOrderMarks: false,
      pageScaling: 'lockratio',
      pagePositioning: 'centered',
      mainForeEdgePaddingPt: 20,
      bindingEdgePaddingPt: 10,
      topEdgePaddingPt: 0,
      bottomEdgePaddingPt: 0,
      sigFormat: 'standardsig',
      sigLength: 4,
      customSigLength: [0],
      foreEdgePaddingPt: 0,
      wackySpacing: 'wacky_pack',
      flyleafs: 1,
      sewingMarksEnabled: true,
      sewingMarkLocation: 'all',
      sewingMarksMarginPt: 0,
      sewingMarksAmount: 2,
      sewingMarksTapeWidthPt: 20,
      paperSizeCustomWidth: 0,
      paperSizeCustomHeight: 0,
    },
  },
  page_numbers_signature_with_sewing_and_margin: {
    input: 'example_page_numbers.pdf',
    config: {
      printFile: 'both',
      sourceRotation: 'none',
      rotatePage: false,
      paperSize: 'A4',
      paperSizeUnit: 'pt',
      printerType: 'duplex',
      paperRotation90: false,
      pageLayout: 'sextodecimo',
      cropMarks: false,
      cutMarks: false,
      pdfEdgeMarks: false,
      sigOrderMarks: false,
      pageScaling: 'lockratio',
      pagePositioning: 'centered',
      mainForeEdgePaddingPt: 20,
      bindingEdgePaddingPt: 10,
      topEdgePaddingPt: 0,
      bottomEdgePaddingPt: 0,
      sigFormat: 'standardsig',
      sigLength: 4,
      customSigLength: [0],
      foreEdgePaddingPt: 0,
      wackySpacing: 'wacky_pack',
      flyleafs: 1,
      sewingMarksEnabled: true,
      sewingMarkLocation: 'all',
      sewingMarksMarginPt: 0,
      sewingMarksAmount: 2,
      sewingMarksTapeWidthPt: 20,
      paperSizeCustomWidth: 0,
      paperSizeCustomHeight: 0,
    },
  },
};
