export const testCases = {
  basic_duplex_folio: {
    input: 'example_page_numbers.pdf',
    config: {
      printFile: 'both',
      sourceRotation: 'none',
      rotatePage: false,
      paperSize: 'A4',
      paperSizeUnit: 'pt',
      printerType: 'duplex',
      paperRotation90: false,
      pageLayout: 'folio',
      cropMarks: false,
      cutMarks: false,
      pdfEdgeMarks: false,
      sigOrderMarks: false,
      pageScaling: 'lockratio',
      pagePositioning: 'centered',
      mainForeEdgePaddingPt: 0,
      bindingEdgePaddingPt: 0,
      topEdgePaddingPt: 0,
      bottomEdgePaddingPt: 0,
      sigFormat: 'standardsig',
      sigLength: 4,
      customSigLength: [0],
      foreEdgePaddingPt: 0,
      wackySpacing: 'wacky_pack',
      flyleafs: 1,
      sewingMarksEnabled: false,
      sewingMarkLocation: 'all',
      sewingMarksMarginPt: 72,
      sewingMarksAmount: 3,
      sewingMarksTapeWidthPt: 36,
      paperSizeCustomWidth: 0,
      paperSizeCustomHeight: 0,
    },
  },
};
