# Simple workflow for deploying static content to GitHub Pages
name: Deploy PR preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
    inputs:
      destination:
        description: 'Define destination base path'
        required: true
        default: 'manual_run'

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.repository == 'momijizukamori/bookbinder-js'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base=https://momijizukamori.github.io/bookbinder-js/pr-preview/pr-${{ github.event.pull_request.number }}
        if: github.event.action != 'closed'
      - uses: rossjrw/pr-preview-action@v1.6.0
        continue-on-error: true
        with:
          source-dir: dist
          umbrella-dir: pr-preview
          action: auto
